version: '3.8'

services:
  postgres:
    container_name: rails-postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twt_development
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
    restart: always
  postgres_test:
    container_name: rails-postgres-test
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twt_test
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg-test:/data/postgres
    restart: always
