default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twt_development
  port: 5432

test:
  <<: *default
  database: twt_test
  port: 5433

production:
  <<: *default
  database: twt_production
  username: twt
  password: <%= ENV["TWT_DATABASE_PASSWORD"] %>
