default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: twt_development

test:
  <<: *default
  database: twt_test

production:
  <<: *default
  database: twt_production
  username: twt
  password: <%= ENV["TWT_DATABASE_PASSWORD"] %>
